---
title: "Example dashboard with static data"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    theme: yeti
---


```{r setup, include=FALSE}
library(tidyverse)
# library(googlesheets4)
library(flexdashboard)
library(plotly)
library(readr)
```

```{r get-data, message=FALSE, include=FALSE}
remote_data <- read_csv("Datos_Ejemplo.csv")
```

## Row

### Categories {.value-box}

```{r}
# Find the number of unique categories
n_categories <- remote_data %>% distinct(Category) %>% nrow()

# Show the number in a special valueBox (note the {.value-box} CSS class
# above—that applies the CSS class to the HTML output and makes it render
# correctly)
valueBox(value = n_categories, icon = "fas fa-users")
```

### Total {.value-box}

```{r}
# Get a total of all the counts
total <- sum(remote_data$Count)

# Show the number in a valueBox
valueBox(value = total, icon = "fas fa-cubes")
```

## Row

###

```{r}
# Make a basic column plot
library(plotly)

plot_ly(remote_data,
        x = ~Category,
        y = ~Count,
        type = "bar",
        text = ~paste("Categoría:", Category, "<br>Count:", Count),
        hoverinfo = "text")

```
